int : 0 , 1 , 3....
float: 34.5 , 25.236
bool: True or False
Str: x = "Welcome to skills for future training " - object
complex: 3 + 4j

In [16]:
x = ["India" , 1947 , "Delhi", 200]
x

['India', 1947, 'Delhi', 200]

In [17]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [18]:
x.append("Karnatka")
x

['India', 1947, 'Delhi', 200, 'Karnatka']

In [19]:
x.insert(0,"Independece")
x

['Independece', 'India', 1947, 'Delhi', 200, 'Karnatka']

In [20]:
# strip cases
y = "19M"
a = y.rstrip("M")
int(a)

19

In [21]:
x[3]

'Delhi'

In [22]:
x[1:3]

['India', 1947]

In [23]:
len(x)

6

In [25]:
t = ("Yahiya" , 12 , "Mysuru")
t

('Yahiya', 12, 'Mysuru')

In [26]:
dir(tuple)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [27]:
# Dictionary
d1 = {"id":101, "name": "India", "age": 200 , "city": "Delhi"}
d1

{'id': 101, 'name': 'India', 'age': 200, 'city': 'Delhi'}

In [28]:
d1["name"]

'India'

In [29]:
d1.get("name")

'India'

In [30]:
del d1["city"]

In [31]:
d1

{'id': 101, 'name': 'India', 'age': 200}

In [33]:
s1 = {1,4,7,9,12}
s2 = {4,6,12,8,15}

In [34]:
s1.union(s2)

{1, 4, 6, 7, 8, 9, 12, 15}

In [35]:
s1.intersection(s2)

{4, 12}

In [37]:
# list comprehension - without
data = [23,14,56,72,90]
new_data = []
for x in data:
    if x%2==0:
        new_data.append(x)
new_data

[14, 56, 72, 90]

In [38]:
# If list comprehension is used!
data1 = [x for x in data if x%2==0]
data1

[14, 56, 72, 90]

In [41]:
pip install pandas numpy matplotlib seaborn

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
data = [23,14,56,72,90]
np.mean(data)

np.float64(51.0)

In [3]:
np.min(data)

np.int64(14)

In [4]:
a = [1,3,5,6]
b=[4,5,6,7]
arr1 = np.array(a)
arr2 = np.array(b)

In [6]:
arr2

array([4, 5, 6, 7])

In [8]:
arr1 *arr2

array([ 4, 15, 30, 42])

In [9]:
arr1.ndim

1

In [10]:
arr1.shape

(4,)

In [11]:
arr1.dtype

dtype('int64')

In [12]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr3.ndim

2

In [14]:
arr3.shape

(3, 3)

In [15]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [17]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [18]:
np.random.randint(10,100,5)

array([75, 82, 19, 45, 51], dtype=int32)

In [19]:
np.random.uniform(10,100,50)

array([78.33550603, 51.63702881, 32.65110165, 20.06850181, 62.94241912,
       56.87228288, 69.10482723, 40.41178595, 27.79566911, 23.28018162,
       65.89472183, 78.3483612 , 12.87849423, 41.85490145, 87.08008397,
       26.75296604, 84.45859066, 36.65176125, 21.60078149, 80.99740126,
       37.55389714, 24.61002286, 46.90861599, 52.73845142, 28.65203779,
       11.040649  , 88.77378175, 74.50202415, 52.86455162, 96.63278643,
       15.57269402, 36.42753612, 81.15104829, 29.04240104, 58.50517649,
       60.9839693 , 15.00557136, 18.24709006, 74.15204825, 66.30599065,
       18.03446566, 47.73516259, 73.71056946, 32.21331379, 97.77928831,
       64.24894269, 96.45138452, 70.41229818, 64.4789543 , 10.37334941])

In [21]:
np.random.rand(100)

array([0.7332737 , 0.94997522, 0.19875674, 0.20172026, 0.89236146,
       0.1061567 , 0.39582202, 0.79698199, 0.18460317, 0.54524958,
       0.66442806, 0.53394733, 0.8636439 , 0.1400652 , 0.93997711,
       0.729715  , 0.92592067, 0.57162285, 0.92293145, 0.74990305,
       0.38924021, 0.61041068, 0.38456809, 0.06303153, 0.88660268,
       0.53055562, 0.46040922, 0.62928747, 0.49304363, 0.88079377,
       0.92086053, 0.67774512, 0.36807013, 0.69854379, 0.93201271,
       0.24094148, 0.99912893, 0.49117842, 0.32545218, 0.74611876,
       0.99564595, 0.60974771, 0.29747879, 0.27804773, 0.94297569,
       0.69643485, 0.31447698, 0.06549315, 0.06091719, 0.76354962,
       0.86583611, 0.50156408, 0.52631592, 0.35151403, 0.60512349,
       0.17144664, 0.25873583, 0.97081972, 0.9173853 , 0.82517104,
       0.33874614, 0.44244652, 0.00500225, 0.59107927, 0.94376094,
       0.81797174, 0.73882662, 0.34015805, 0.91408676, 0.39358407,
       0.23772933, 0.34386471, 0.14473054, 0.97679629, 0.51494

In [22]:
np.random.randint(10,100,12).reshape(4,3)

array([[81, 25, 16],
       [26, 52, 12],
       [12, 70, 68],
       [99, 40, 54]], dtype=int32)

In [23]:
r = 45.7
np.floor(r)

np.float64(45.0)

In [24]:
np.ceil(r)

np.float64(46.0)

In [25]:
z = np.random.randint(1,100,12)

In [26]:
z = sorted(z)

In [27]:
z

[np.int32(8),
 np.int32(8),
 np.int32(11),
 np.int32(26),
 np.int32(41),
 np.int32(44),
 np.int32(44),
 np.int32(63),
 np.int32(63),
 np.int32(86),
 np.int32(91),
 np.int32(99)]

In [28]:
np.percentile(z,75)

np.float64(68.75)

In [29]:
import pandas as pd

In [32]:
renewable_sources = ["solar","wind","hydro power", "Geothermal","Biomass"]

data = {
    "Project" : ["solar farm","Wind turbine","Hydro power","solar Roof","Geothermal plant"],
    "Technology" : ["solar","wind","hydro","solar","geothermal"],
    "Capacity (MW)":[150,300,200,50,100],
    "Costs (Millions $)":[200,400,350,100,250],
    "Location":["California","Texas","Washington","Nevada","Chicago"],
    "Completion Year":[2023,2024,2022,2025,2023]
}

In [33]:
# create a pandas series for renewable energy sources
renewable_series = pd.Series(renewable_sources)
print("Renewable Energy Sources are:")
print(renewable_series)

Renewable Energy Sources are:
0          solar
1           wind
2    hydro power
3     Geothermal
4        Biomass
dtype: object


In [34]:
# Create a Dataframe for green tech projects
df = pd.DataFrame(data)
print("Green Technology Projects DataFrame")
print(df)

Green Technology Projects DataFrame
            Project  Technology  Capacity (MW)  Costs (Millions $)  \
0        solar farm       solar            150                 200   
1      Wind turbine        wind            300                 400   
2       Hydro power       hydro            200                 350   
3        solar Roof       solar             50                 100   
4  Geothermal plant  geothermal            100                 250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4     Chicago             2023  


In [36]:
df["Project"]

0          solar farm
1        Wind turbine
2         Hydro power
3          solar Roof
4    Geothermal plant
Name: Project, dtype: object

In [39]:
print(df["Project"])

0          solar farm
1        Wind turbine
2         Hydro power
3          solar Roof
4    Geothermal plant
Name: Project, dtype: object


In [40]:
df["Location"]

0    California
1         Texas
2    Washington
3        Nevada
4       Chicago
Name: Location, dtype: object

In [46]:
# Want to print only high capacity projects (>100 MW)
hcp =df[df["Capacity (MW)"]>100]
hcp

Project Technology  Capacity (MW)  Costs (Millions $)    Location  \
0    solar farm      solar            150                 200  California   
1  Wind turbine       wind            300                 400       Texas   
2   Hydro power      hydro            200                 350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022

In [48]:
# Add new col
df["Cost per MW"] = df["Costs (Millions $)"] /df["Capacity (MW)"]
df

Project  Technology  Capacity (MW)  Costs (Millions $)  \
0        solar farm       solar            150                 200   
1      Wind turbine        wind            300                 400   
2       Hydro power       hydro            200                 350   
3        solar Roof       solar             50                 100   
4  Geothermal plant  geothermal            100                 250   

     Location  Completion Year  Cost per MW  
0  California             2023     1.333333  
1       Texas             2024     1.333333  
2  Washington             2022     1.750000  
3      Nevada             2025     2.000000  
4     Chicago             2023     2.500000

In [49]:
# Aggregation 
total_capacity = df["Capacity (MW)"].sum()
total_cost=df["Costs (Millions $)"].sum()
print("The total Capacity of all the projects are: ",total_capacity)
print("The total cost of the projects :",total_cost)

The total Capacity of all the projects are:  800
The total cost of the projects : 1300


In [50]:
# Grouping of data
grouped_data = df.groupby("Technology")["Capacity (MW)"].sum()
grouped_data

Technology
geothermal    100
hydro         200
solar         200
wind          300
Name: Capacity (MW), dtype: int64

## Day 3:Numpy

In [2]:
import numpy as np

energy_consumption = np.array([1200,3400,2900,1800,2500])
print("Energy Consumption in mWh for different energy sources")
energy_consumption

Energy Consumption in mWh for different energy sources


array([1200, 3400, 2900, 1800, 2500])

In [3]:
# calculate the total energy consumption
total_consumption = np.sum(energy_consumption)
print(f"The total energy consumption is {total_consumption} MWh")

The total energy consumption is 11800 MWh


In [4]:
# calculate the mean energy consumption
mean_consumption = np.mean(energy_consumption)
print(f"The mean energy consumption is {mean_consumption} MWh")

The mean energy consumption is 2360.0 MWh


In [5]:
# calculate the standard deviation for energy consumption
std_ec = np.std(energy_consumption)
std_ec

np.float64(781.2809993849844)

In [6]:
print(f"The standard deviation of energy consumption is {std_ec} MWh")

The standard deviation of energy consumption is 781.2809993849844 MWh


In [7]:
# Reshape the array 
reshaped_array = energy_consumption.reshape((5,1))
print("Reshape array is")
print(reshaped_array)

Reshape array is
[[1200]
 [3400]
 [2900]
 [1800]
 [2500]]


# Data Preprocessing

In [18]:
import pandas as pd
import numpy as np
# sample data with missing values
data= {
    "Energy Source":["Solar","Wind","Hydropower","Geothermal","Biomass","Nuclear"],
    "Energy Consumption (MWh)":[1200,np.nan,2900,np.nan,2500,3200],
    "Cost (millions $)":[200,400,np.nan,150,250,np.nan]
}

In [19]:
# Create a dataframe
df= pd.DataFrame(data)
print(df)

  Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                    1200.0              200.0
1          Wind                       NaN              400.0
2    Hydropower                    2900.0                NaN
3    Geothermal                       NaN              150.0
4       Biomass                    2500.0              250.0
5       Nuclear                    3200.0                NaN


## Handle the missing values:
-Removing (drop) mv
-impute (fill) mv-mean

In [20]:
# Remove rows with missing value 
cleaned_df=df.dropna()
cleaned_df

Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                    1200.0              200.0
4       Biomass                    2500.0              250.0

## Imputation to add or fill
-- With mean
__ forward/backward filling

In [22]:
#impute missing values with the mean for energy consumption
df["Energy Consumption (MWh)"].fillna(df["Energy Consumption (MWh)"].mean(),inplace=True)
df["Cost (millions $)"].fillna(df["Cost (millions $)"].mean(),inplace=True)
df

C:\Users\myahi_\AppData\Local\Temp\ipykernel_15292\3393485841.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Energy Consumption (MWh)"].fillna(df["Energy Consumption (MWh)"].mean(),inplace=True)
C:\Users\myahi_\AppData\Local\Temp\ipykernel_15292\3393485841.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are settin

Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                    1200.0              200.0
1          Wind                     250.0              400.0
2    Hydropower                    2900.0              250.0
3    Geothermal                     250.0              150.0
4       Biomass                    2500.0              250.0
5       Nuclear                    3200.0              250.0

In [23]:
# Forward filling missinig values
ff_df = df.fillna(method="ffill")
ff_df

C:\Users\myahi_\AppData\Local\Temp\ipykernel_15292\1739668566.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ff_df = df.fillna(method="ffill")


Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                    1200.0              200.0
1          Wind                     250.0              400.0
2    Hydropower                    2900.0              250.0
3    Geothermal                     250.0              150.0
4       Biomass                    2500.0              250.0
5       Nuclear                    3200.0              250.0

In [24]:
pip install scikit-learn


  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 8.2 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/11.1 MB 3.0 MB/s eta 0:00:04
   ----- ---------------------------------- 1.6/11.1 MB 2.5 MB/s eta 0:00:04
   ------ --------------------------------- 1.8/11.1 MB 2.2 MB/s eta 0:00:05
   ------- -------------------------------- 2.1/11.1 MB 1.9 MB/s eta 0:00:05
   ------- -------------------------------- 2.1/11.1 MB 1.9 MB/s eta 0:00:05
   ------- -------------------------------- 2.1/11.1 MB 1.9 MB/s eta 0:00:05
   --------- ------------------------------ 2.6/11.1 MB 1.4 MB/s eta 0:00:06
   ---------- ----------------------------- 2.9/11.1 MB 1.4 MB/s eta 0:00:06
   ----------- ---------------------------- 3.1/11.1 MB 1.4 MB/s eta 0:00:06
   ----------- ------------

In [26]:
# Data Preprocessing  - Normalization
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[["Energy Consumption (MWh)","Cost (millions $)"]] = scaler.fit_transform(df[["Energy Consumption (MWh)","Cost (millions $)"]])
df

Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                  0.322034                0.2
1          Wind                  0.000000                1.0
2    Hydropower                  0.898305                0.4
3    Geothermal                  0.000000                0.0
4       Biomass                  0.762712                0.4
5       Nuclear                  1.000000                0.4

In [27]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[["Energy Consumption (MWh)","Cost (millions $)"]] = scaler.fit_transform(df[["Energy Consumption (MWh)","Cost (millions $)"]])
df

Energy Source  Energy Consumption (MWh)  Cost (millions $)
0         Solar                 -0.427028      -6.546537e-01
1          Wind                 -1.212209       1.963961e+00
2    Hydropower                  0.978032       1.817029e-16
3    Geothermal                 -1.212209      -1.309307e+00
4       Biomass                  0.647430       1.817029e-16
5       Nuclear                  1.225984       1.817029e-16

## Encoding - One hot encoding

In [29]:
ohe_df =pd.get_dummies(df,columns=["Energy Source"])
print(ohe_df)

   Energy Consumption (MWh)  Cost (millions $)  Energy Source_Biomass  \
0                 -0.427028      -6.546537e-01                  False   
1                 -1.212209       1.963961e+00                  False   
2                  0.978032       1.817029e-16                  False   
3                 -1.212209      -1.309307e+00                  False   
4                  0.647430       1.817029e-16                   True   
5                  1.225984       1.817029e-16                  False   

   Energy Source_Geothermal  Energy Source_Hydropower  Energy Source_Nuclear  \
0                     False                     False                  False   
1                     False                     False                  False   
2                     False                      True                  False   
3                      True                     False                  False   
4                     False                     False                  False   
5       

In [30]:
# Feature engineering
ohe_df["Consumption per Million $"]= ohe_df["Energy Consumption (MWh)"]/ohe_df["Cost (millions $)"]
ohe_df

Energy Consumption (MWh)  Cost (millions $)  Energy Source_Biomass  \
0                 -0.427028      -6.546537e-01                  False   
1                 -1.212209       1.963961e+00                  False   
2                  0.978032       1.817029e-16                  False   
3                 -1.212209      -1.309307e+00                  False   
4                  0.647430       1.817029e-16                   True   
5                  1.225984       1.817029e-16                  False   

   Energy Source_Geothermal  Energy Source_Hydropower  Energy Source_Nuclear  \
0                     False                     False                  False   
1                     False                     False                  False   
2                     False                      True                  False   
3                      True                     False                  False   
4                     False                     False                  False   
5                     False                     False                   True   

   Energy Source_Solar  Energy Source_Wind  Consumption per Million $  
0                 True               False               6.522961e-01  
1                False                True              -6.172264e-01  
2                False               False               5.382589e+15  
3                False               False               9.258396e-01  
4                False               False               3.563122e+15  
5                False               False               6.747189e+15